export const ACTIONS = {
  NOTIFY: "NOTIFY",
  AUTH: "AUTH",
  // GLOBAL_LOADING: "GLOBAL_LOADING",
  LOADING: "LOADING",
  SIDEPANEL: "SIDEPANEL",
  LOGIN_MODAL: "LOGIN_MODAL",
  REGISTER_MODAL: "REGISTER_MODAL",
};
